version: '3'
services:
  order-db:
    image: postgres:latest
    container_name: order-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 10

  order-svc:
    build:
      context: ..
      dockerfile: ./order-svc/Dockerfile
    container_name: order-svc
    ports:
      - "5050:8080"
    environment:
      POSTGRES_HOST: order-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      KAFKA_BROKERS: kafka:29092
    depends_on:
      order-db:
        condition: service_healthy
    networks:
      - my-network
      - svc-network
      - kafka-network

networks:
  my-network:
    driver: bridge
  kafka-network:
    external: true
  svc-network:
    external: true