version: '3'
services:
  restaurant-db:
    image: postgres:latest
    container_name: restaurant-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 10

  restaurant-svc:
    build:
      context: ..
      dockerfile: ./restaurant-svc/Dockerfile
    container_name: restaurant-svc
    ports:
      - "7070:8080"
    environment:
      SECRET: ${SECRET}
      POSTGRES_HOST: restaurant-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      restaurant-db:
        condition: service_healthy
    networks:
      - my-network
      - svc-network

networks:
  my-network:
    driver: bridge
  svc-network:
    external: true