version: '3'
services:
  customer-db:
    image: postgres:latest
    container_name: customer-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 10

  customer-svc:
    build:
      context: ..
      dockerfile: ./customer-svc/Dockerfile
    container_name: customer-svc
    ports:
      - "8080:8080"
    environment:
      SECRET: ${SECRET}
      POSTGRES_HOST: customer-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      customer-db:
        condition: service_healthy
    networks:
      - my-network
      - svc-network

networks:
  my-network:
    driver: bridge
  svc-network:
    external: true